safe: true
lsi: false
paginate: 1000
highlighter: pygments
permalink: /p/:title/

collections:
  pages:
    output: true

kb_baseurl: https://bekt.net
kb_feed_title: Posts by Kanat
kb_github_repo: https://github.com/Bekt/bekt.net

exclude:
  - README.md
  - netlify.toml