[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Server = "yoloman"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "same-origin"

[[redirects]]
  from = "https://blog.bekt.net"
  to = "https://bekt.net"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.bekt.net/*"
  to = "https://bekt.net/:splat"
  status = 301
  force = true
